language: "php"
addons:
  sonarcloud:
    organization: "overdueweevil2"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner -X -Dsonar.login=${SONAR_TOKEN}
